### ISSUE TITLE
Support secrets in image config

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/neuro-flow#36]
To be precise, we need to be able to:
 
* declare secrets as volumes
* pass env and volumes to an image config:

```
volumes:
  gh_private:
    remote: secret:key
    mount: /mount/path/file.txt

images:
  cloudinary:
    ref: image:${{ flow.id }}:v1.0
    dockerfile: ${{ flow.workspace }}/Dockerfile
    context: ${{ flow.workspace }}
    env:
       VALUE=secret:key
    volumes:
       -- ${{ volumes.gh_private.ref_ro }}
```
