### ISSUE TITLE
[FR] Customize OPEN_TMPL and CLOSE_TMPL

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuromation/neuro-flow#47]
## Context & problem description
Currently, neuro-flow context files use template variables with syntax `${{var.subvar}}` without the ability to change OPEN and CLOSE literals to smth else like `$[[var.subvar]]`.
It results in an incompatibility issue when using a cookiecutter templating tool.
Example of use-case from potential `live.yml` file in the project template:
```yml
...
jobs:
  develop:
    image: $[[ images.{{ cookiecutter.project_slug }}.ref ]]
    bash:
...
```

## Needs
Since we are planning to rewrite the project template (`neuro project init`) from makefile to neuro-flow, such compatibility would be great to have. For instance, by exposing parameter `--open_tmpl`, `--close-tmpl`, or storing them in a config file of inside `.neuro` folder.

## Alternatives considered
1. We've checked the ability to customize jinja2 parser, used in cookiecutter, but such feature [will](https://github.com/cookiecutter/cookiecutter/issues/704#issuecomment-636328527) be available in cookiecutter 2.0. Unfortunately, we will not be able to update cookiecutter since the airflow package (that we use in neuro-airflow-plugin) uses the old version of cookiecutter.

**Comment by YevheniiSemendiak** [comment]
cc @yartem , @mariyadavydova

**Comment by mariyadavydova** [comment]
@YevheniiSemendiak Just in case - didn't you try to split the declarations, so that the cookiecutter and neuro-flow tags are never inside each other? E.g. you declare a `train` image with `{{ cookiecutter.project_slug }}` and then reference it as `${{ images.train.ref }}`? Does cookiecutter break in this case?

**Comment by mariyadavydova** [comment]
Well, it does. I tried to make a tiny template and got a pretty expected 
```
Unable to create file 'live.yml'
Error message: 'flow' is undefined
```

**Comment by mariyadavydova** [comment]
@asvetlov The fastest solution I can see right now is indeed to change the opening and closing tokens to something like `$[[` and `]]` in neuro-flow. What do you think?

**Comment by YevheniiSemendiak** [comment]
> We don't know when cookiecutter 2.0 

That is true, but while we are using it only inside of the template, one of the workarounds may be building from a fixed commit in the cookiecutter master branch. I've made it locally and managed to scatter the template successfully. But it also did require some adaptations in `cookiecutter` code ([click](https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/find.py#L22), [click](https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/generate.py#L223)). It is rather raw implementation.(

> didn't you try to split the declarations

No reason for doing so, since Jinja2's parsing tokens are [these](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment) and thus while parsing our neuro-flow YML files, jinja will consider all neuro-flow tokens `&{{` and `}}` as variable_start_string and variable_end_string respectively.

> change the opening and closing tokens to something like $[[

I would prefer to provide the possibility to parametrize them, thus enabling others to combine template parsers smoothly. However, simply changing [them](https://github.com/neuromation/neuro-flow/blob/master/neuro_flow/expr.py#L327) might also work.

**Comment by mariyadavydova** [comment]
It turned out that jinia has escaping functionality: https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping
In our case it's enough to hide most of the live.yml under {% raw %}:

```
kind: live
title: Sentiment Analysis Training

volumes:
  project:
    remote: storage:{{ cookiecutter.project_slug }}
    mount: /project
    local: .
{% raw %}
images:
  pytorch:
    ref: image:${{ flow.id }}:v1.0
    dockerfile: ${{ flow.workspace }}/Dockerfile
    context: ${{ flow.workspace }}

jobs:
  train:
    image: ${{ images.pytorch.ref }}
    preset: gpu-small
    multi: True
    volumes:
      - ${{ volumes.project.ref_rw }}
    bash: |
        cd ${{ volumes.project.mount }}
        python train.py --model_name bert_spc --dataset restaurant
{% endraw %}
```
